### ISSUE TITLE
`register` causes SystemStackError: stack level too deep w/ MongoLab

### ISSUE THREAD

**Issue by zethussuen** [dblock/slack-gamebot#38]
Running on heroku with MongoLab free tier. Only thing of note here is that Netflix is behind a SAML-based-single-sign-on (SSO). However, the bot can connect to the slack service fine. `hi` returns fine. Once `register` is run, the app dumps this error:

```
2015-10-09T18:41:07.995217+00:00 app[web.1]: Puma starting in single mode...
2015-10-09T18:41:07.995251+00:00 app[web.1]: * Version 2.14.0 (ruby 2.2.1-p85), codename: Fuchsia Friday
2015-10-09T18:41:07.995254+00:00 app[web.1]: * Min threads: 0, max threads: 16
2015-10-09T18:41:07.995255+00:00 app[web.1]: * Environment: production
2015-10-09T18:41:09.125541+00:00 app[web.1]: * Listening on tcp://0.0.0.0:12740
2015-10-09T18:41:09.183190+00:00 app[web.1]: I, [2015-10-09T18:41:09.183027 #3]  INFO -- : Welcome 'smashbot' to the 'Netflix' team at https://netflix.slack.com/.
2015-10-09T18:41:09.129859+00:00 app[web.1]: Use Ctrl-C to stop
2015-10-09T18:41:09.637428+00:00 heroku[web.1]: State changed from starting to up
2015-10-09T18:41:09.681063+00:00 app[web.1]: I, [2015-10-09T18:41:09.680954 #3]  INFO -- : Successfully connected to https://netflix.slack.com/.
2015-10-09T18:41:30.395612+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
2015-10-09T18:41:30.395616+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
2015-10-09T18:41:30.395621+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
2015-10-09T18:41:30.395626+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
2015-10-09T18:41:30.395631+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
2015-10-09T18:41:30.395643+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:116:in `connection'
2015-10-09T18:41:30.395644+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/operation/read.rb:52:in `block in execute'
2015-10-09T18:41:30.395647+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `[]'
2015-10-09T18:41:30.395649+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `block (3 levels) in flush'
2015-10-09T18:41:30.395654+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `map'
2015-10-09T18:41:30.395657+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `block (2 levels) in flush'
2015-10-09T18:41:30.395662+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:185:in `ensure_connected'
2015-10-09T18:41:30.395667+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
2015-10-09T18:41:30.395671+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
2015-10-09T18:41:30.393237+00:00 app[web.1]: SystemStackError: stack level too deep
*2015-10-09T18:41:30.393247+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/protocol/reply.rb:129:in `unauthorized?'*
2015-10-09T18:41:30.393249+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/operation/read.rb:51:in `block in execute'
2015-10-09T18:41:30.393251+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `[]'
2015-10-09T18:41:30.395676+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
2015-10-09T18:41:30.395681+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-10-09T18:41:30.395686+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
2015-10-09T18:41:30.393253+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `block (3 levels) in flush'
2015-10-09T18:41:30.393254+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `map'
2015-10-09T18:41:30.393258+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `block (2 levels) in flush'
2015-10-09T18:41:30.393260+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:185:in `ensure_connected'
2015-10-09T18:41:30.395690+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
2015-10-09T18:41:30.395695+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:631:in `logging'
2015-10-09T18:41:30.395700+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:602:in `flush'
2015-10-09T18:41:30.393262+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
2015-10-09T18:41:30.393266+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
2015-10-09T18:41:30.395703+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:406:in `process'
2015-10-09T18:41:30.395708+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
2015-10-09T18:41:30.395713+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/operation/read.rb:56:in `block (2 levels) in execute'
2015-10-09T18:41:30.395718+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
2015-10-09T18:41:30.395721+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
2015-10-09T18:41:30.395726+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
2015-10-09T18:41:30.395746+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
2015-10-09T18:41:30.395747+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
2015-10-09T18:41:30.393270+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
2015-10-09T18:41:30.393273+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-10-09T18:41:30.393276+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
2015-10-09T18:41:30.393280+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
2015-10-09T18:41:30.393286+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:631:in `logging'
2015-10-09T18:41:30.393289+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:602:in `flush'
2015-10-09T18:41:30.393294+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:406:in `process'
2015-10-09T18:41:30.395751+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
2015-10-09T18:41:30.395754+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:116:in `connection'
2015-10-09T18:41:30.395757+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/operation/read.rb:52:in `block in execute'
2015-10-09T18:41:30.395762+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `[]'
2015-10-09T18:41:30.395768+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `block (3 levels) in flush'
2015-10-09T18:41:30.395771+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `map'
2015-10-09T18:41:30.395776+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `block (2 levels) in flush'
2015-10-09T18:41:30.395781+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:185:in `ensure_connected'
2015-10-09T18:41:30.393300+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
2015-10-09T18:41:30.395786+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
2015-10-09T18:41:30.395790+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
2015-10-09T18:41:30.395795+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
2015-10-09T18:41:30.395800+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
```

**Comment by dblock** [comment]
So it looks like the problem is your MongoDB connection, not slack. Did you set an ENV variable for production?

**Comment by dblock** [comment]
I would connect with a console, see https://github.com/dblock/slack-gamebot/blob/master/DEBUGGING.md, and try to do something like `User.count` and see what happens. You should have the same error.

**Comment by zethussuen** [comment]
The mongolab_uri is correctly set in the config. Connecting via console and running `User.count` (following https://github.com/dblock/slack-gamebot/blob/master/DEBUGGING.md) returned:

```
SystemStackError: stack level too deep
	from /app/vendor/bundle/ruby/2.2.0/gems/bson-3.2.4/lib/bson/hash.rb:43:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/bson-3.2.4/lib/bson/hash.rb:43:in `block in to_bson'
	from /app/vendor/bundle/ruby/2.2.0/gems/bson-3.2.4/lib/bson/encodable.rb:57:in `encode_with_placeholder_and_null'
	from /app/vendor/bundle/ruby/2.2.0/gems/bson-3.2.4/lib/bson/hash.rb:42:in `to_bson'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/protocol/message.rb:173:in `serialize_selector'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/protocol/message.rb:325:in `serialize'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/connection.rb:171:in `block in write'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/connection.rb:169:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/connection.rb:169:in `write'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:604:in `block (2 levels) in flush'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:185:in `ensure_connected'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
... 9286 levels...
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `call'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
	from /app/vendor/bundle/ruby/2.2.0/gems/moped-2.0.7/lib/moped/query.rb:128:in `first'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:191:in `block in first_with_cache'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:135:in `with_cache'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:190:in `first_with_cache'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:199:in `block (2 levels) in first'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:545:in `with_sorting'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:198:in `block in first'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:457:in `try_cache'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:197:in `first'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `first'
	from /app/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/findable.rb:144:in `first'
```

**Comment by zethussuen** [comment]
Have some updates. Read through some of the issues, seems like this thread has some insightful information http://stackoverflow.com/questions/32951455/mongoid-infinite-loop-on-query re:sharding on MongoLab

**Comment by dblock** [comment]
Interesting! I would have liked to confirm whether `options: connect: :sharded` solves the problem.

**Comment by micahrowland** [comment]
I was getting this same error and switched to MongoHQ/Compose as zethussuen suggested (probably should have tried dblock's suggestion but I was trying to make things speedy) in an attempt to fix it.

Once I made the switch to MongoHQ and dropped the free MongoLab tier, I got a different error (which I just created a separate issue for):
 
![image](https://cloud.githubusercontent.com/assets/15351343/10774197/0807d568-7cbd-11e5-8166-5f448740b78c.png)

**Comment by dblock** [comment]
I was able to repro, upgraded to Mongoid5 and tested with MongoLab. That worked. Heroku also notes that MongoLab only works with mongoid5 [here](https://devcenter.heroku.com/articles/mongolab).
