### ISSUE TITLE
Register causing a bug (possibly related to . in username?)

### ISSUE THREAD

**Issue by micahrowland** [dblock/slack-gamebot#39]
Register is causing a bug with the following message: "undefined method 'match' for nil:NilClass'"

See screenshot:

![image](https://cloud.githubusercontent.com/assets/15351343/10774143/c6280e2e-7cbc-11e5-8d69-4274fdfa9564.png)

**Comment by dblock** [comment]
Oh interesting, I bet it's about that username with a period. Can you get a stack trace from a `heroku logs --tail` please?

**Comment by micahrowland** [comment]
C:\Users\Micah Rowland>heroku logs --tail --app fs-chessbot
2015-10-27T22:56:13.794493+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
2015-10-27T22:56:13.794494+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
2015-10-27T22:56:13.794496+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:631:in `logging'
2015-10-27T22:56:13.794499+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:602:in `flush'
2015-10-27T22:56:13.794501+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:406:in `process'
2015-10-27T22:56:13.794509+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
2015-10-27T22:56:13.794503+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
2015-10-27T22:56:13.794506+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/operation/read.rb:56:in `block (2 levels) in execute'
2015-10-27T22:56:13.794532+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
2015-10-27T22:56:13.794529+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
2015-10-27T22:56:13.794534+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
2015-10-27T22:56:13.794530+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
2015-10-27T22:56:13.794536+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:116:in `connection'
2015-10-27T22:56:13.794533+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
2015-10-27T22:56:13.794561+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:607:in `block (2 levels) in flush'
2015-10-27T22:56:13.794555+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/operation/read.rb:52:in `block in execute'
2015-10-27T22:56:13.794558+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:608:in `block (3 levels) in flush'
2015-10-27T22:56:13.794556+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:608:in `[]'
2015-10-27T22:56:13.794559+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:607:in `map'
2015-10-27T22:56:13.794563+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:193:in `block in ensure_connected'
2015-10-27T22:56:13.794626+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
2015-10-27T22:56:13.794570+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
2015-10-27T22:56:13.794629+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:116:in `connection'
2015-10-27T22:56:13.794566+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
2015-10-27T22:56:13.794568+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
2015-10-27T22:56:13.794628+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
2015-10-27T22:56:13.794629+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:189:in `ensure_connected'
2015-10-27T22:56:13.794633+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrum
ent'
2015-10-27T22:56:13.794635+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:631:in `logging'
2015-10-27T22:56:13.794630+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
2015-10-27T22:56:13.794634+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
2015-10-27T22:56:13.794642+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
2015-10-27T22:56:13.794633+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `inst
rument'
2015-10-27T22:56:13.794637+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:602:in `flush'
2015-10-27T22:56:13.794628+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
2015-10-27T22:56:13.794630+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
2015-10-27T22:56:13.794634+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
2015-10-27T22:56:13.794638+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:406:in `process'
2015-10-27T22:56:13.794667+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/query.rb:129:in `block in first'
2015-10-27T22:56:13.794645+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:663:in `read'
2015-10-27T22:56:13.794647+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:426:in `query'
2015-10-27T22:56:13.794668+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/cluster.rb:249:in `block in with_primary'
2015-10-27T22:56:13.794671+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:219:in `block in ensure_primary'
2015-10-27T22:56:13.794671+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/executable.rb:25:in `execute'
2015-10-27T22:56:13.794679+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/retryable.rb:30:in `call'
2015-10-27T22:56:13.794672+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/node.rb:218:in `ensure_primary'
2015-10-27T22:56:13.794674+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/cluster.rb:248:in `with_primary'
2015-10-27T22:56:13.794676+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
2015-10-27T22:56:13.794680+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
2015-10-27T22:56:13.794711+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/query_cache.rb:135:in `with_cache'
2015-10-27T22:56:13.794711+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/query_cache.rb:190:in `first_with_cache'
2015-10-27T22:56:13.794683+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
2015-10-27T22:56:13.794707+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
moped-2.0.7/lib/moped/query.rb:128:in `first'
2015-10-27T22:56:13.794710+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/query_cache.rb:191:in `block in first_with_cache'
2015-10-27T22:56:13.794733+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:457:in `try_cache'
2015-10-27T22:56:13.794730+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:545:in `with_sorting'
2015-10-27T22:56:13.794761+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/commands/base.rb:59:in `invoke'
2015-10-27T22:56:13.794731+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:198:in `block in first'
2015-10-27T22:56:13.794736+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `first'
2015-10-27T22:56:13.794758+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/commands/base.rb:67:in `block in invoke'

2015-10-27T22:56:13.794759+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/commands/base.rb:59:in `each_pair'
2015-10-27T22:56:13.794713+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:199:in `block (2 levels) in first'

2015-10-27T22:56:13.794734+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:197:in `first'
2015-10-27T22:56:13.794754+00:00 app[web.1]: /app/slack-gamebot/models/user.rb:4
1:in `find_create_or_update_by_slack_id!'
2015-10-27T22:56:13.794755+00:00 app[web.1]: /app/slack-gamebot/commands/registe
r.rb:6:in `call'
2015-10-27T22:56:13.794763+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/hooks/message.rb:9:in `block in message'

2015-10-27T22:56:13.794765+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/hooks/message.rb:9:in `each'
2015-10-27T22:56:13.794767+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/hooks/message.rb:9:in `detect'
2015-10-27T22:56:13.794770+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/hooks/message.rb:9:in `message'
2015-10-27T22:56:13.794790+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/app.rb:74:in `block (2 levels) in client
'
2015-10-27T22:56:13.794789+00:00 app[web.1]: /app/config/initializers/slack-ruby
-bot/hooks/message.rb:6:in `message'
2015-10-27T22:56:13.794792+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-client-0.3.0/lib/slack/real_time/client.rb:104:in `call'
2015-10-27T22:56:13.794793+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-client-0.3.0/lib/slack/real_time/client.rb:104:in `block in dispatch'

2015-10-27T22:56:13.794795+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-client-0.3.0/lib/slack/real_time/client.rb:103:in `each'
2015-10-27T22:56:13.794797+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-client-0.3.0/lib/slack/real_time/client.rb:103:in `dispatch'
2015-10-27T22:56:13.794798+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-client-0.3.0/lib/slack/real_time/client.rb:52:in `block (3 levels) in
start!'
2015-10-27T22:56:13.794810+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:31:in `call'
2015-10-27T22:56:13.794812+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:31:in `block in emi
t'
2015-10-27T22:56:13.794813+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:30:in `each'
2015-10-27T22:56:13.794814+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:30:in `emit'
2015-10-27T22:56:13.794814+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
faye-websocket-0.10.0/lib/faye/websocket/api/event_target.rb:45:in `dispatch_eve
nt'
2015-10-27T22:56:13.794817+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
faye-websocket-0.10.0/lib/faye/websocket/api.rb:104:in `receive_message'
2015-10-27T22:56:13.794819+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
faye-websocket-0.10.0/lib/faye/websocket/api.rb:38:in `block in initialize'
2015-10-27T22:56:13.794821+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:31:in `call'
2015-10-27T22:56:13.794826+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:30:in `each'
2015-10-27T22:56:13.794824+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:31:in `block in emi
t'
2015-10-27T22:56:13.794829+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:30:in `emit'
2015-10-27T22:56:13.794832+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/hybi.rb:403:in `emit_message'
2015-10-27T22:56:13.794834+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/hybi.rb:386:in `emit_frame'
2015-10-27T22:56:13.794837+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/hybi.rb:118:in `parse'
2015-10-27T22:56:13.794857+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
websocket-driver-0.5.4/lib/websocket/driver/client.rb:57:in `parse'
2015-10-27T22:56:13.794858+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
faye-websocket-0.10.0/lib/faye/websocket/api.rb:143:in `parse'
2015-10-27T22:56:13.794861+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
faye-websocket-0.10.0/lib/faye/websocket/client.rb:77:in `receive_data'
2015-10-27T22:56:13.794861+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
2015-10-27T22:56:13.794863+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
2015-10-27T22:56:13.794876+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-client-0.3.0/lib/slack/real_time/client.rb:38:in `start!'
2015-10-27T22:56:13.794877+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/app.rb:47:in `block in start!'
2015-10-27T22:56:13.794877+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/app.rb:45:in `loop'
2015-10-27T22:56:13.794879+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/app.rb:45:in `start!'
2015-10-27T22:56:13.794880+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/
slack-ruby-bot-0.4.4/lib/slack-ruby-bot/app.rb:28:in `run'
2015-10-27T22:56:13.794882+00:00 app[web.1]: config.ru:7:in `block (2 levels) in
<main>'

**Comment by dblock** [comment]
@micahrowland That's missing the actual error, you might want to get a longer stack. Heroku logs takes -n or something I think. I just want the top 10 lines below the exception.

**Comment by dblock** [comment]
Check that you have set `RACK_ENV=production` and that you have either `MONGOHQ_URL` or `MONGOLAB_URI`.

**Comment by dblock** [comment]
I think this is the same problem as #38. I updated to Mongoid5 and improved errors with the database connection just in case. Please check out HEAD? Reopen if that didn't fix it.

**Comment by dblock** [comment]
Btw @micahrowland it looks like you're setting up a chess bot. You'll probably want #25 and #26. LMK if you need help or want to try to implement those.

**Comment by micahrowland** [comment]
@dblock re-deployed your updated version and confirm register now works (using MongoLab).  Nice fix!  Thank you!  And thanks for the tips on #25 and #26.  I have not coded in years so I'm not sure you'd want me attempting to implement but if I can manage to knock the rust off maybe I will give it a shot. =)
