### ISSUE TITLE
Undefined method error for hooks

### ISSUE THREAD

**Issue by cakejelly** [dblock/slack-gamebot#43]
I'm trying to integrate the `user_change` hook into a bot i'm working on at the moment but getting an undefined method error any time the hook is triggered in slack. 

I've included a sample stack trace and snippets below to demonstrate how i've set the hook up. Am I doing something wrong here or is this a bug?

```
E, [2015-12-09T11:48:49.279250 #11425] ERROR -- : undefined method `user_change' for #<SlackRubyBot::App:0x007fae4245cb10> (NoMethodError)
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-bot-0.4.5/lib/slack-ruby-bot/app.rb:74:in `block (2 levels) in client'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-client-0.4.0/lib/slack/real_time/client.rb:104:in `call'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-client-0.4.0/lib/slack/real_time/client.rb:104:in `block in dispatch'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-client-0.4.0/lib/slack/real_time/client.rb:103:in `each'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-client-0.4.0/lib/slack/real_time/client.rb:103:in `dispatch'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-client-0.4.0/lib/slack/real_time/client.rb:52:in `block (3 levels) in start!'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:31:in `call'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:31:in `block in emit'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:30:in `each'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:30:in `emit'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket/api/event_target.rb:45:in `dispatch_event'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket/api.rb:106:in `receive_message'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket/api.rb:40:in `block in initialize'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:31:in `call'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:31:in `block in emit'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:30:in `each'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/event_emitter.rb:30:in `emit'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/hybi.rb:403:in `emit_message'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/hybi.rb:386:in `emit_frame'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/hybi.rb:118:in `parse'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/websocket-driver-0.5.4/lib/websocket/driver/client.rb:57:in `parse'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket/api.rb:145:in `parse'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket/client.rb:71:in `receive_data'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-client-0.4.0/lib/slack/real_time/client.rb:38:in `start!'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-bot-0.4.5/lib/slack-ruby-bot/app.rb:47:in `block in start!'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-bot-0.4.5/lib/slack-ruby-bot/app.rb:45:in `loop'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-bot-0.4.5/lib/slack-ruby-bot/app.rb:45:in `start!'
/Users/jakekelly/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slack-ruby-bot-0.4.5/lib/slack-ruby-bot/app.rb:28:in `run'
/Users/jakekelly/dev/feedback-bot/config.ru:10:in `block (2 levels) in <main>'
```
feedback-bot/hooks/user_change.rb
```
module FeedbackBot
  module Hooks
    module UserChange
      extend SlackRubyBot::Hooks::Base

      def user_change(_client, data)
        p data
      end
    end
  end
end
```

feedback-bot/app.rb
```
module FeedbackBot
  class App < SlackRubyBot::App
    include FeedbackBot::Hooks::UserChange
  end
end
```

**Comment by dblock** [comment]
This issue should be in slack-ruby-bot, right? You're just looking at an example here...

This looks correct to me, but notice that it's trying to call `user_change` on `SlackRubyBot::App`, not on `FeedbackBot::App`, I suspect you use an `instance` from `SlackRubyBot`, and it doesn't create an instance of your class but of the superclass. This was fixed in https://github.com/dblock/slack-ruby-bot/pull/33, would you give slack-ruby-bot#HEAD a try and if it works I'll cut a release?

**Comment by dblock** [comment]
I'll close this, pretty sure this is the issue, reopen if it's something else.

**Comment by cakejelly** [comment]
Oops sorry yeah my bad! I was looking at how you were implementing hooks here and opened the issue in the wrong place.

I will try what you mentioned and reopen if something else is up :) Thanks for the help

**Comment by cakejelly** [comment]
Works on slack-ruby-bot#HEAD. Thanks again!
