### ISSUE TITLE
Stack traces logged for non-fatal exceptions

### ISSUE THREAD

**Issue by dblock** [dblock/slack-gamebot#73]
```
2016-01-04T22:10:23.594880+00:00 app[web.1]: E, [2016-01-04T22:10:23.594757 #3] ERROR -- : hector can't play. There's already a challenge between hector and jake. (ArgumentError)
2016-01-04T22:10:23.594884+00:00 app[web.1]: /app/config/initializers/slack-ruby-bot/hooks/message.rb:8:in `rescue in message'
2016-01-04T22:10:23.594888+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/newrelic-slack-ruby-bot-0.1.0/lib/newrelic-slack-ruby-bot/instrumentation.rb:23:in `block in message_with_new_relic'
2016-01-04T22:10:23.594890+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/newrelic-slack-ruby-bot-0.1.0/lib/newrelic-slack-ruby-bot/instrumentation.rb:22:in `message_with_new_relic'
2016-01-04T22:10:23.594891+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.5.4/lib/slack-ruby-bot/server.rb:96:in `block (2 levels) in client'
2016-01-04T22:10:23.594893+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.5.0/lib/slack/real_time/client.rb:145:in `each'
2016-01-04T22:10:23.594894+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.5.0/lib/slack/real_time/client.rb:145:in `dispatch'
2016-01-04T22:10:23.594896+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:39:in `call'
2016-01-04T22:10:23.594898+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:38:in `emit'
2016-01-04T22:10:23.594898+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:38:in `each'
2016-01-04T22:10:23.594892+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.5.0/lib/slack/real_time/client.rb:146:in `call'
2016-01-04T22:10:23.594899+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket/api/event_target.rb:45:in `dispatch_event'
2016-01-04T22:10:23.594900+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket/api.rb:106:in `receive_message'
2016-01-04T22:10:23.594901+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket/api.rb:40:in `block in initialize'
2016-01-04T22:10:23.594901+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.3/lib/websocket/driver/event_emitter.rb:39:in `call'
```

**Comment by dblock** [comment]
Closed via https://github.com/dblock/slack-gamebot/commit/b1940bbaf16c41dae897e876b081addac92b1dc5.
