### ISSUE TITLE
eventmachine not initialized errors are fatal

### ISSUE THREAD

**Issue by dblock** [dblock/slack-gamebot#93]
This is isn't supposed to ever happen since https://github.com/dblock/slack-gamebot/commit/e97eb87de98139691d40753932bd6925e4ea473e, but still is. 

```
I, [2016-02-15T11:59:45.777251 #5632]  INFO -- : Starting team game=chess, name=tradingsnack, id=T0LUJRSSW.
E, [2016-02-15T11:59:46.412685 #5632] ERROR -- : OP Online: eventmachine not initialized: evma_signal_loopbreak, restarting in 1 second(s).
EventMachine::ConnectionNotBound: unknown connection: 335
/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
config.ru:20:in `block (2 levels) in <main>'
E, [2016-02-15T11:59:46.428313 #5632] ERROR -- : Lendahand: eventmachine not initialized: evma_signal_loopbreak, restarting in 1 second(s).
E, [2016-02-15T11:59:46.432688 #5632] ERROR -- : listen loop error: unknown connection: 335 (EventMachine::ConnectionNotBound)
E, [2016-02-15T11:59:46.432761 #5632] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
E, [2016-02-15T11:59:46.432800 #5632] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
E, [2016-02-15T11:59:46.432823 #5632] ERROR -- : config.ru:20:in `block (2 levels) in <main>'
E, [2016-02-15T13:18:32.869657 #5632] ERROR -- : RuntimeError: Team Lendahand is already registered.
  /app/slack-gamebot/api/endpoints/teams_endpoint.rb:65:in `block (2 levels) in <class:TeamsEndpoint>'
  /app/vendor/bundle/ruby/2.2.0/gems/grape-0.13.0/lib/grape/endpoint.rb:51:in `call'
  /app/vendor/bundle/ruby/2.2.0/gems/grape-0.13.0/lib/grape/endpoint.rb:51:in `block (2 levels) in generate_api_method'
  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
  /app/vendor/bundle/ruby/2.2.0/gems/grape-0.13.0/lib/grape/endpoint.rb:50:in `block in generate_api_method'
  /app/vendor/bundle/ruby/2.2.0/gems/grape-0.13.0/lib/grape/endpoint.rb:254:in `call'
E, [2016-02-15T14:07:42.114696 #5632] ERROR -- : RuntimeError: Team M&C Saatchi is already registered.
  /app/slack-gamebot/api/endpoints/teams_endpoint.rb:65:in `block (2 levels) in <class:TeamsEndpoint>'
  /app/vendor/bundle/ruby/2.2.0/gems/grape-0.13.0/lib/grape/endpoint.rb:51:in `call'
  /app/vendor/bundle/ruby/2.2.0/gems/grape-0.13.0/lib/grape/endpoint.rb:51:in `block (2 levels) in generate_api_method'
  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
  /app/vendor/bundle/ruby/2.2.0/gems/grape-0.13.0/lib/grape/endpoint.rb:50:in `block in generate_api_method'
  /app/vendor/bundle/ruby/2.2.0/gems/grape-0.13.0/lib/grape/endpoint.rb:254:in `call'
E, [2016-02-15T14:08:06.286067 #5632] ERROR -- : Slack::Web::Api::Error: code_already_used
  /app/vendor/bundle/ruby/2.2.0/bundler/gems/slack-ruby-client-3b0e56c542f9/lib/slack/web/faraday/response/raise_error.rb:9:in `on_complete'
  /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
  /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
  /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
  /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
  /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
```

**Comment by dblock** [comment]
We no longer use EventMachine here.
