### ISSUE TITLE
Validation of Team failed, deactivating a team.

### ISSUE THREAD

**Issue by dblock** [dblock/slack-gamebot#99]
```
E, [2016-03-03T04:58:17.207647 #161] ERROR -- : ***: account_inactive, team will be deactivated.
Mongoid::Errors::Validations: 
message:
  Validation of Team failed.
summary:
  The following errors were found: Challenges is invalid
resolution:
  Try persisting the document with valid data or remove the validations.
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.2/lib/mongoid/persistable.rb:78:in `fail_due_to_validation!'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.2/lib/mongoid/persistable/updatable.rb:73:in `update!'
/app/slack-gamebot/models/team.rb:37:in `deactivate!'
/app/slack-gamebot/service.rb:68:in `rescue in restart!'
/app/slack-gamebot/service.rb:63:in `restart!'
/app/slack-gamebot/server.rb:22:in `block in restart!'
/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in `times'
/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in `run_deferred_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
config.ru:20:in `block (2 levels) in <main>'
E, [2016-03-03T04:58:17.334831 #161] ERROR -- : listen loop error: "\nmessage:\n  Validation of Team failed.\nsummary:\n  The following errors were found: Challenges is invalid\nresolution:\n  Try persisting the document with valid data or remove the validations." (Mongoid::Errors::Validations)
E, [2016-03-03T04:58:17.334938 #161] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.2/lib/mongoid/persistable.rb:78:in `fail_due_to_validation!'
E, [2016-03-03T04:58:17.334967 #161] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.2/lib/mongoid/persistable/updatable.rb:73:in `update!'
E, [2016-03-03T04:58:17.334986 #161] ERROR -- : /app/slack-gamebot/models/team.rb:37:in `deactivate!'
E, [2016-03-03T04:58:17.335006 #161] ERROR -- : /app/slack-gamebot/service.rb:68:in `rescue in restart!'
E, [2016-03-03T04:58:17.335024 #161] ERROR -- : /app/slack-gamebot/service.rb:63:in `restart!'
E, [2016-03-03T04:58:17.335042 #161] ERROR -- : /app/slack-gamebot/server.rb:22:in `block in restart!'
E, [2016-03-03T04:58:17.335059 #161] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:in `call'
E, [2016-03-03T04:58:17.335076 #161] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
E, [2016-03-03T04:58:17.335094 #161] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in `times'
E, [2016-03-03T04:58:17.335111 #161] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in `run_deferred_callbacks'
E, [2016-03-03T04:58:17.335129 #161] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
E, [2016-03-03T04:58:17.335146 #161] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
E, [2016-03-03T04:58:17.335163 #161] ERROR -- : config.ru:20:in `block (2 levels) in <main>'
```

**Comment by dblock** [comment]
This was fixed in https://github.com/dblock/slack-gamebot/commit/24e94f03cee1181b0f4076907d6b7a2c33d00220.
